### ISSUE TITLE
Trackpoint Marker Tools do not work with blender 4.3.0

### ISSUE THREAD

**Issue by twaldschmidt** [imagiscope/EarthStudioTools#28]
When executing Create Markers, the following python error is shown:

> Python: Traceback (most recent call last):
>   File "/home/tom/.config/blender/4.3/scripts/addons/GES_Panel.py", line 368, in execute
>     makemarkers()
>   File "/home/tom/.config/blender/4.3/scripts/addons/GES_Panel.py", line 931, in makemarkers
>     mk2 = bpy.data.objects.new('Marker_' + newtext, mk.data.copy())
>                                                     ^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'copy'

I would appreciate a fix.

**Comment by twaldschmidt** [comment]
Even though I'm neither a Python not a Blender expert, it seems that
line 931
`mk2 = bpy.data.objects.new('Marker_' + newtext, mk.data.copy())
`
accesses the internal Blender API, which might have changed.
See: https://docs.blender.org/api/current/bpy.data.html#

```
mk2 = mk.copy()
mk2.name = 'Marker_' + newtext
```
fixes it for me.

Shall I create a pull request?
